import "./globals.css";

import Script from "next/script";
import { environments } from "~/src/environments";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script
        async
        src={`https://www.googletagmanager.com/gtag/js?id=${environments.GOOGLE_ANALYTICS_ID}`}
      />
      <Script>
        {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '${environments.GOOGLE_ANALYTICS_ID}');`}
      </Script>
    </html>
  );
}
