name: Chromatic
on:
  push:
    branches:
      - main

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: pnpm install
      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          buildScriptName: build:storybook
          projectToken: ${{ secrets.COMPONENTS_CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/components
  root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: pnpm install
      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          buildScriptName: build:storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
