name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          corepack: true
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com
          scope: noahluftyang
      - name: Install dependencies
        run: pnpm install
      - name: Create Release Pull Request or Publish to GPR
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
